### ISSUE TITLE
[JCAP] Editor decision on document JCAP_081P_0615 

### ISSUE THREAD

**Issue by XiaoleiMeng** [tommasotreu/HIGHRESOLUTIONIMAGING#33] opened 2015-08-05 13:20 UTC
Hi, guys,
We have received the report about our paper. Please see the email from the referee I forwarded and the links below. There are 15 questions on the report. I will open some new issues depending on each of them. Some are easily solved. Some need to be discussed. Hope we can return it soon.
Best,
Xiao-Lei

From: JCAP Editorial Office <jcap-eo@jcap.sissa.it>
Date: 2015年7月23日 GMT+8下午10:43:55
To: Xiao-Lei Meng <xlmeng919@gmail.com>
Cc: JCAP Editorial Office <jcap-eo@jcap.sissa.it>
Subject: [JCAP] Editor decision on document JCAP_081P_0615

Authors:    Xiao-Lei Meng, Tommaso Treu, Adriano Agnello, Matthew W. Auger, Kai Liao, Philip J. Marshall
Title:    Precision cosmology with time delay lenses: high resolution imaging  requirements

Dear Xiao-Lei,

Your paper was sent to an expert referee who has now returned a report. The referee finds your work interesting and useful and has some recommendations for improvement. When you submit a revised version include a reply to referee with a detailed listing of changes made. Your paper will be returned to the referee before a decision on acceptance can be made.

Standard email follows below:

Please connect to the status page for your submission JCAP_081P_0615

http://jcap.sissa.it/jcap/author/docPage.jsp?docPgType=work&docId=JCAP_081P_0615

for which you  are kindly requested to make  major revisions according
to  the editor  report available  there  (after clicking  on the  link
"report" a pop up will open with a link to the pdf file).

The rules  for submission of  your revision will  be sent to you  in a
separate message.

Sincerely yours,

Asantha Cooray
JCAP Editor

![jcap_081p_0615_edrep016130715_1](https://cloud.githubusercontent.com/assets/8421271/9086502/5faafbfc-3bb7-11e5-9f26-a40f2c727b4e.png)
![jcap_081p_0615_edrep016130715_2](https://cloud.githubusercontent.com/assets/8421271/9086556/a1c37852-3bb7-11e5-9269-bff30a07b2d0.png)
![jcap_081p_0615_edrep016130715_3](https://cloud.githubusercontent.com/assets/8421271/9086561/a9804a16-3bb7-11e5-859f-006d6ea5aae2.png)
![jcap_081p_0615_edrep016130715_4](https://cloud.githubusercontent.com/assets/8421271/9086565/b006d22e-3bb7-11e5-937b-cf4684b62310.png)

**Comment by tommasotreu** [comment] 2015-08-05 19:46
Xiao-Lei, this is not an issue. This is a document that should be in the repository. The issue is complete response to the referee. Please upload the report on the repository and close this issue.

**Closed** 2015-08-06 13:06 UTC
